### ISSUE TITLE
early stop to the join process

### ISSUE THREAD

**Issue by kaiwang0112006** [MSeal/agglom_cluster#11]
Like the network of physicists in the [paper](https://arxiv.org/pdf/cond-mat/0309508v1.pdf), my subgraph of large graph can still be split into smaller communities. So is there a way to control the cluster process to tell it to stop when the size of each subgraph reach a limit?

**Comment by MSeal** [comment]
Not currently. It could be added but the definition is a little vague programatically. Especially since the algorithm is bottom up (starts with n clusters of size 1). I think it'd be easier to define a target number of clusters and halt further computation. However, unless your graph is really big simply computing all optimal clusters than picking the ideal number of clusters out of the dendrogram is easy. The code already supports this when you call `dendrogram.clusters(my_ideal_cluster_count)`.

The algorithm more defines stepping to the next best arrangement of clusters independent of cluster sizes. For example in the worst case, every next-best cluster may be adding a cluster of size 1 to the largest cluster. This would mean you always have k size 1 clusters and one n-k size cluster. In this case when would you consider stopping computation / selecting an ideal cluster arrangement? If you have an answer to that which want to achieve then it would likely be an extension of the dendrogram implementation to have alternative cluster selectors other than you-pick and optimal-quality.

**Comment by kaiwang0112006** [comment]
Thanks, I think I will have to find a  ideal cluster count, which is not a issue of the algorithm. There's still  another issue I want to discuss about this repository between version 1.0.2 and 2.0. I will close this issue and open another.
