### ISSUE TITLE
Greedy cluster algorithm

### ISSUE THREAD

**Issue by kirantpatil** [MSeal/agglom_cluster#14]
Hi,

I would like to know whether it is the same algorithm which is used in [Leaflet.MarkerCluster](https://github.com/Leaflet/Leaflet.markercluster).

If it is not then please point me to the right "Greedy cluster algorithm" package/module implemented in  python/go/rust.

Thanks.

**Comment by MSeal** [comment]
Without digging really deeply into that codebase and risking an ignorant answer here, that library does not appear to be using a well defined clustering algorithm. It seems to just be picking first elements by grid and putting cells to the closest first point on each render if they fit in the zoom box.

Additionally there is no "right Greedy cluster algorithm". Greedy just implies it's making simplifying assumptions to produce a less accurate result for much cheaper computation time. And there isn't a canonical clustering answer so there's no "right" clustering algorithm.

This algorithm is a low parameter, efficient solution to the clustering problem. Thus it _is_ a greedy clustering algorithm implemented in Python. There's a few others available now since I originally wrote this library. In particular http://scikit-learn.org/stable/modules/clustering.html is a good, if more complex, implementation which did not exist several years ago which can stand in as an alternative to this library.
